---
title: "Introduction to toolPhD"
author: 'Tien-Cheng Wang'
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: no
    toc: no
  html_document:
    df_print: paged
    toc: yes
vignette: >
  %\VignetteIndexEntry{Introduction to toolPhD}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
csl: https://tinyurl.com/apa6-meta-analysis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr);suppressWarnings(library(dplyr));
suppressWarnings(library(ggplot2));library(tidyr);
library(kableExtra);library(knitr);library(purrr)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```




Then the package can be loaded using the function
```{r}
library(toolPhD)
```



## Structure overview of toolPhD

toolPhD contains different functions to calculate stability indices, including:
```{r,echo=FALSE}
library(toolPhD)

```



<!-- ## Build-in data set -->

<!-- The default data set `Data` is the subset of $APSIM$ simulated wheat data set, which includes 5 genotypes in 4 locations for 4 years, with 2 nitrogen application rates, 2 sowing dates, and 2 $CO_2$ levels of treatments [@casadebaig2016]. Full dataset used in the publication see here [click](https://zenodo.org/record/4729636). -->

<!-- `Data` in this package is a data frame with 640 observations and 8 variables. -->

<!-- : Data Structure -->

<!-- | Parameters | Number | Description | -->
<!-- | :--- | ---: | :--- | -->
<!-- | Trait |   | Wheat yield ($kg~ha^{-1}$).|  -->
<!-- | Genotype | 5 | varieties.| -->
<!-- | Environment | 128 | unique combination of environments for each genotype.| -->
<!-- | Year | 4 | years.| -->
<!-- | Sites | 4 | locations.| -->
<!-- | Nitrogen | 2 | nitrogen application levels.| -->
<!-- | $CO_2$ | 2 | $CO_2$ concentration levels.| -->
<!-- | Sowing | 2 | sowing dates.| -->

\clearpage

## Examples
```{r}
rm(list=ls())
library(toolPhD)
### load data

dplyr::glimpse(iris)
view_df(iris)
```
\clearpage



